### ISSUE TITLE
Main JS Math.ceil

### ISSUE THREAD

**Issue by mohsenhosseini** [Bear1110/adaptive-huffman-coding-FGK#1]
Hi, 
May I know why you didnt use Math.ceil instead of 
`let gg = 0
if(output.length % 8 !=0)
    gg++
var buffer = new Uint8Array(output.length / 8 +gg);`

for example: 
`var buffer = new Uint8Array(Math.ceil(output.length/8))`

Thanks

**Comment by Bear1110** [comment]
Thank you.
Actually I finish this for homework.
So I didn't do much research for something.
Just use the concept that I though first.

**Comment by Bear1110** [comment]
48e90e45a147f936ea4d5d4ae350f7bea9281c32

I fix it.
